name: PHP Lint

on:
  pull_request:
    paths:
      - "libraries/php/**"
      - "libraries/composer.*"
      - "libraries/phpunit.yml"
      - ".github/workflows/php-lint.yml"
jobs:
  build:
    name: PHP Lint
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: [5.6, 7.4, 8.3]
        dependency-version: [prefer-lowest, prefer-stable]

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          working_dir: "libraries"

      - name: run lint
        working-directory: libraries
        run: vendor/bin/php-cs-fixer fix -v --dry-run --diff .

      - name: run tests
        working-directory: libraries
        run: vendor/bin/phpunit php/tests
